spring:
  application:
    name: gateway

server:
  port: 7071



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5
    registry-fetch-interval-seconds: 5
